<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <a href="queryUsers" target="right">用户信息</a><br>
    <a href="班级信息" target="right">班级信息</a><br>
    <a href="学生信息" target="right">学生信息</a><br>
    <a href="" target="right">课程信息</a><br>
    <a href="" target="right">成绩信息</a><br>
    <a href="" target="right">爱好信息</a><br>
    <a href="" target="_top">退出系统</a><br>
</body>
</html>